### PR TITLE
Code Updated

### PR DESCRIPTION
**Pull request by KannanKrish**
Updates I have done:

1) Import3DModelFileAsync to load the file.

Example:

```cs
loadedObjectGuid = await view3D.Import3DModelFileAsync("/Assets/Models/uploads_files_2270154_tajmahal.STL");
```

2) File scope namespace updated to reduce the code indentation.
3) Global Namespace added.
4) Importing Universal Scene Description (Usdz) files

### CODE REVIEW

**Comment by simutaroman** [comment]
also, please
- add example of using your added method in to TestServer project
- after your changes, the TestWebAsm project doesn't want to compile
- resolve conflicts with main branch

**Comment by KannanKrish** [comment]
TestServer project updated to .Net 8.
In page2.razor I have added the new method for loading 3D model. Previous code also works.
`
builder.Services.AddBlazor3DFileTypes();
`
This is line is important to add 3D file MIME Types.

**Comment by KannanKrish** [comment]
TestServer project updated to .Net 8.
In page2.razor I have added the new method for loading 3D model. Previous code also work.
`
builder.Services.AddBlazor3DFileTypes();
`
This is line is important

**Comment by KannanKrish** [comment]
Screenshot (25)

```cs
// Loading the 3D Model from other site not working
loadedObjectGuid = await view3D.Import3DModelFileAsync("https://threejs.org/examples/models/stl/ascii/slotted_disk.stl");
```

```cs
// Loading static files are working fine
loadedObjectGuid = await view3D.Import3DModelFileAsync("/Assets/Models/uploads_files_2270154_tajmahal.STL");
```

**Pull request closed without merging**
